{% set version = "master" %}
{% set pybind_version = "stable" %}

package:
  name: opengv
  version: {{ version }}

source:
  - url: https://github.com/paulinus/opengv/archive/{{ version }}.tar.gz
    fn: opengv-{{ version }}.tar.gz
    sha256: 6041128957dc15d269abc68368058fbc8041b705b24e901b4e54b1d7b64b149a
  - url: https://github.com/pybind/pybind11/archive/{{ pybind_version }}.tar.gz
    fn: pybind-{{ pybind_version }}.tar.gz
    sha256: 24c820c1bf501890564745cc078464726623b17ba43b4bb38be93045281b7052
    folder: python/pybind11

build:
    number: 0

requirements:
  build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
    - ninja
    - python
    - numpy
  host:
    - suitesparse {{ suitesparse }}
    - eigen {{ eigen }}
    - python
    - numpy
  run:
    - suitesparse {{ suitesparse }}
    - python
    - numpy

test:
  imports:
    - pyopengv

about:
  home: http://laurentkneip.github.io/opengv
  license: ANU
  summary: A library for solving calibrated central and non-central geometric vision problems

extra:
  recipe-maintainers:
    - v-turin
